version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb